name: loadfile_baustro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Librerias Web
  http: ^0.13.3
  dio: ^4.0.4

  # Librarias de Control
  provider: ^6.0.3
  path: ^1.8.2

  # Responsitividad
  sizer: ^2.0.15

  # control de aplicaciones de escritorio
  bitsdojo_window: ^0.1.5
  #  flutter_acrylic: ^1.0.0
  file_picker: ^5.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Paquete de gestion de notificaciones locales
  # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^12.0.2

  # Paquete para gestionar Toast en pantalla
  # https://pub.dev/packages/bot_toast
  bot_toast: ^4.0.1

  # Paquete para Gestion de Audio
  # https://pub.dev/packages/audioplayer
  audioplayers: ^1.1.1

  # Paquete UI para manipulacion de imagenes SVG
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.0.3

  # Paquete UI para construccion de pantalla de configuraciones
  # https://pub.dev/packages/flutter_settings_ui
  flutter_settings_ui: ^2.0.1

  # Paquete de Themas pre-configurados
  # https://pub.dev/packages/flex_color_scheme
  flex_color_scheme: ^6.0.1

  url_launcher: ^6.1.6
  format: ^1.2.0


dev_dependencies:
  msix: ^3.6.6
  flutter_test:
    sdk: flutter
  test: ^1.19.5
  # Para guardar datos localmente
  build_runner: ^2.0.0
  objectbox_generator: any
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  # Biblioteca de análisis estático que le ayuda a analizar y mejorar la calidad de su código.
  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.13.0
  colorize: any
  # Para iconos
  flutter_launcher_icons: ^0.10.0

# Opciones de parametros para el analizador de la configuracion
# https://pub.dev/packages/dart_code_metrics
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else

# Configuraciones para crear empaquetamiento en Windows
# command: flutter pub run msix:create
# https://pub.dev/packages/msix
msix_config:
  display_name: FLoad File - Shops
  publisher_display_name: Vague Solutions
  identity_name: com.vaguesolutions.dev
  msix_version: 1.0.0.0
  logo_path: C:\Users\Usuario\Desktop\Coders\loadfile_baustro\assets\img\logo.png
#  capabilities: internetClient, location, microphone, webcam


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/img/
    - assets/gif/
    - assets/templates/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
analyzer:
  enable-experiment:
    - control-flow-collections

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir:
    lib: db
    test: db_test
  # Or optionally specify the lib and test output folder separately.
  # output_dir:
  #   lib: custom
  #   test: other